import { SaveSystem } from '../systems/SaveSystem.js';
import { GameScene } from './GameScene.js';
const FONT='"Malgun Gothic", system-ui, sans-serif';
const fmtPlay=s=>{s=Math.floor(s||0);return`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;};
export class TitleScene{
  constructor(game){this.game=game;this.t=0;this.screen='main';this.buttons=[];this.focus=0;}
  init(){this.game.sound.ensure?.();this.game.sound.setDucked(false);this.focus=0;if(typeof document!=='undefined'){document.getElementById('tracker')?.classList.add('hidden');window.__fitGameScale?.();}}
  update(dt){this.t+=dt;const i=this.game.input;
    if(this.screen==='main'){
      const has=SaveSystem.hasAnySave(),count=3;if(i.hit('ArrowUp'))this.focus=(this.focus-1+count)%count;if(i.hit('ArrowDown'))this.focus=(this.focus+1)%count;
      if(i.hit('Enter','Space','KeyE')){if(this.focus===0)this.startNew();else if(this.focus===1&&has){this.screen='load';this.focus=0;}else if(this.focus===2){this.screen='options';this.focus=0;}}
      if(i.hit('Digit1','Numpad1','KeyN'))this.startNew();if(i.hit('Digit2','Numpad2','KeyC')&&has){this.screen='load';this.focus=0;}if(i.hit('Digit3','Numpad3','KeyO')){this.screen='options';this.focus=0;}if(i.click)this.clickButtons(i.click);
    }else if(this.screen==='load'){
      const rows=SaveSystem.list();if(i.hit('Escape')){this.screen='main';this.focus=0;return;}if(i.hit('ArrowUp'))this.focus=(this.focus-1+rows.length)%rows.length;if(i.hit('ArrowDown'))this.focus=(this.focus+1)%rows.length;if(i.hit('Enter','Space','KeyE')){const r=rows[this.focus];if(r?.meta)this.loadSlot(r.id);}if(i.click)this.clickButtons(i.click);
    }else{
      if(i.hit('Escape')){this.screen='main';this.focus=0;return;}if(i.hit('ArrowUp'))this.focus=(this.focus+1)%2;if(i.hit('ArrowDown'))this.focus=(this.focus+1)%2;const step=i.down('ShiftLeft','ShiftRight')?.05:.01;if(this.focus===0&&i.hit('ArrowLeft'))this.game.sound.setBGMVolume(this.game.sound.bgmVolume-step);if(this.focus===0&&i.hit('ArrowRight'))this.game.sound.setBGMVolume(this.game.sound.bgmVolume+step);if(this.focus===1&&i.hit('ArrowLeft'))this.game.sound.setSFXVolume(this.game.sound.sfxVolume-step);if(this.focus===1&&i.hit('ArrowRight')){this.game.sound.setSFXVolume(this.game.sound.sfxVolume+step);this.game.sound.tone(500,.05,'square',.03);}if(i.click)this.handleOptionsClick(i.click);
    }
  }
  clickButtons(p){for(const b of this.buttons){if(p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h&&b.enabled!==false){b.action();return;}}}
  startNew(){this.game.sound.coin();this.game.sound.startBGM();this.game.scenes.set(GameScene,{newGame:true});}
  loadSlot(id){const data=SaveSystem.load(id);if(!data)return;this.game.sound.coin();this.game.sound.startBGM();this.game.scenes.set(GameScene,{save:data,loadedSlot:id});}
  handleOptionsClick(p){const a=this.game.sound,sx=252,sw=176;if(p.y>=147&&p.y<=166&&p.x>=sx&&p.x<=sx+sw){this.focus=0;a.setBGMVolume((p.x-sx)/sw);return;}if(p.y>=212&&p.y<=231&&p.x>=sx&&p.x<=sx+sw){this.focus=1;a.setSFXVolume((p.x-sx)/sw);a.tone(500,.05,'square',.03);return;}for(const b of this.buttons){if(p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h){b.action();return;}}}
  render(ctx){this.drawBg(ctx);if(this.screen==='main')this.renderMain(ctx);else if(this.screen==='load')this.renderLoad(ctx);else this.renderOptions(ctx);}
  drawBg(ctx){ctx.fillStyle='#3d332a';ctx.fillRect(0,0,640,360);for(let y=0;y<360;y+=24){for(let x=((y/24)%2)*20-20;x<640;x+=40){ctx.fillStyle=((x+y)/8)%2?'#493c30':'#42362c';ctx.fillRect(x,y,38,22);}}const glow=.5+.5*Math.sin(this.t*2);ctx.fillStyle=`rgba(235,115,38,${.08+glow*.06})`;ctx.fillRect(0,0,640,360);}
  title(ctx,sub=''){ctx.fillStyle='#1c120d';ctx.fillRect(78,35,484,126);ctx.fillStyle='#7f5935';ctx.fillRect(84,41,472,114);ctx.fillStyle='#4f321f';ctx.fillRect(92,49,456,98);ctx.fillStyle='#d1a45e';ctx.fillRect(106,62,428,3);ctx.fillRect(106,136,428,3);ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#f1d7a2';ctx.font=`bold 24px ${FONT}`;ctx.fillText('형제 대장간',320,91);ctx.fillStyle='#d8ba84';ctx.font=`10px ${FONT}`;ctx.fillText('BLACKSMITH BROTHERS · V0.2.5f',320,117);ctx.fillStyle='#bfa378';ctx.font=`8px ${FONT}`;ctx.fillText(sub||'상호작용·NPC 보조·창고 UX·메시지 큐 핫픽스',320,132);ctx.textAlign='left';}
  renderMain(ctx){this.title(ctx);const has=SaveSystem.hasAnySave(),opts=[{label:'새 게임',enabled:true,action:()=>this.startNew()},{label:'이어하기',enabled:has,action:()=>{this.screen='load';this.focus=0;}},{label:'옵션',enabled:true,action:()=>{this.screen='options';this.focus=0;}}];this.buttons=[];opts.forEach((o,i)=>{const x=210,y=190+i*45,w=220,h=32;this.buttons.push({...o,x,y,w,h});ctx.fillStyle=o.enabled?(i===this.focus?'#4a321f':'#2a1c13'):'#241c17';ctx.fillRect(x,y,w,h);ctx.strokeStyle=i===this.focus?'#f0c665':'#9c7145';ctx.strokeRect(x+.5,y+.5,w-1,h-1);ctx.fillStyle=o.enabled?'#f0d9ad':'#796d60';ctx.font=`11px ${FONT}`;ctx.textAlign='center';ctx.fillText(`${i===this.focus?'▶ ':''}${o.label}`,x+w/2,y+h/2);});ctx.fillStyle='#c3a87a';ctx.font=`8px ${FONT}`;ctx.fillText('↑↓ 이동 · Enter 선택 · 마우스도 사용 가능',320,343);ctx.textAlign='left';}
  renderLoad(ctx){this.title(ctx,'AUTO SAVE와 SAVE 1~6 중 원하는 시점을 선택');this.buttons=[];const slots=SaveSystem.list();slots.forEach((s,i)=>{const x=128,y=168+i*26,w=384,h=23,m=s.meta,enabled=!!m;this.buttons.push({x,y,w,h,enabled,action:()=>this.loadSlot(s.id)});ctx.fillStyle=enabled?(i===this.focus?'#4a321f':'#24170f'):'#30271f';ctx.fillRect(x,y,w,h);ctx.strokeStyle=i===this.focus?'#f0c665':enabled?'#9b7042':'#584b3f';ctx.strokeRect(x+.5,y+.5,w-1,h-1);ctx.fillStyle=enabled?'#f0d7aa':'#776b5f';ctx.font=`bold 8px ${FONT}`;ctx.fillText(`${i===this.focus?'▶ ':''}${s.label}`,x+7,y+9);ctx.font=`7px ${FONT}`;if(m&&!m.corrupt)ctx.fillText(`${m.date} ${m.time} · ${m.gold}G · 명성 ${m.reputation} · ${fmtPlay(m.playTimeSeconds)}`,x+88,y+14);else ctx.fillText(m?.corrupt?'손상된 저장':'비어 있음',x+88,y+14);});ctx.fillStyle='#ead2a7';ctx.textAlign='center';ctx.font=`8px ${FONT}`;ctx.fillText('ESC 뒤로 · ↑↓ 선택 · Enter 불러오기',320,351);ctx.textAlign='left';}
  renderOptions(ctx){this.title(ctx,'전체 세이브에 공통으로 유지되는 오디오 설정');const a=this.game.sound;ctx.fillStyle='#ead5ae';ctx.font=`10px ${FONT}`;ctx.fillText(`${this.focus===0?'▶ ':''}BGM ${Math.round(a.bgmVolume*100)}%`,164,154);this.slider(ctx,252,147,176,a.bgmVolume,this.focus===0);ctx.fillText(`${this.focus===1?'▶ ':''}효과음 ${Math.round(a.sfxVolume*100)}%`,164,219);this.slider(ctx,252,212,176,a.sfxVolume,this.focus===1);ctx.fillStyle='#ae9672';ctx.font=`8px ${FONT}`;ctx.textAlign='center';ctx.fillText('↑↓ 항목 · ←→ 1% · Shift+←→ 5% · ESC 뒤로',320,322);ctx.textAlign='left';}
  slider(ctx,x,y,w,v,focus=false){ctx.fillStyle='#251811';ctx.fillRect(x,y,w,19);ctx.fillStyle='#815b35';ctx.fillRect(x+5,y+8,w-10,4);ctx.fillStyle='#ddb962';ctx.fillRect(x+5,y+8,(w-10)*v,4);ctx.fillStyle='#f1ddaa';ctx.fillRect(x+Math.round((w-12)*v),y+3,7,13);if(focus){ctx.strokeStyle='#f0c665';ctx.strokeRect(x-.5,y-.5,w+1,20);}}
}
